------------------------------------------------------------------------
-- edit/replace/update/improve product icons
------------------------------------------------------------------------
local prod_icons = {
	CARBON_SEAL		= 'PRODUCTS/PRODUCT.MSEAL.DDS',
	STATION_KEY		= 'PRODUCTS/PRODUCT.STATION.OVERRIDE.DDS',
	FISHBAIT_1		= 'COOKINGPRODUCTS/PRODUCT.BAIT.WORMS.DDS',
	FOOD_M_BALL		= 'COOKINGPRODUCTS/PRODUCT.MEAT.BRAIN.DDS',
	FOOD_M_BEETLE	= 'COOKINGPRODUCTS/PRODUCT.MEAT.CARAPACE.DDS',
	FOOD_M_BONE		= 'COOKINGPRODUCTS/PRODUCT.BONE.CRYSTAL.DDS',
	FOOD_M_CAT		= 'COOKINGPRODUCTS/PRODUCT.MEAT.LIVER.DDS',
	FOOD_M_COW		= 'COOKINGPRODUCTS/PRODUCT.MEAT.STEAK1.DDS',
	FOOD_M_CRAB		= 'COOKINGPRODUCTS/PRODUCT.MEAT.CRAB.DDS',
	FOOD_M_DIGGER	= 'COOKINGPRODUCTS/PRODUCT.MEAT.BONEY.DDS',
	FOOD_M_DIPLO	= 'COOKINGPRODUCTS/PRODUCT.MEAT.STEAK2.DDS',
	FOOD_M_DRILL	= 'COOKINGPRODUCTS/PRODUCT.MEAT.SINEW.DDS',
	FOOD_M_FISH		= 'COOKINGPRODUCTS/PRODUCT.MEAT.FISH.DDS',
	FOOD_M_FLYER	= 'COOKINGPRODUCTS/PRODUCT.MEAT.WING.DDS',
	FOOD_M_HORROR	= 'COOKINGPRODUCTS/PRODUCT.MEAT.HORROR.DDS',
	FOOD_M_MEAT		= 'COOKINGPRODUCTS/PRODUCT.MEAT.CHUNKY.DDS',
	FOOD_M_MOLE		= 'COOKINGPRODUCTS/PRODUCT.MEAT.MOLE.DDS',
	FOOD_M_REX		= 'COOKINGPRODUCTS/PRODUCT.MEAT.SCALE.DDS',
	FOOD_M_STRIDER	= 'COOKINGPRODUCTS/PRODUCT.MEAT.SAUSAGE1.DDS',
	FOOD_V_BLOB		= 'COOKINGPRODUCTS/PRODUCT.HONEY.ALT.DDS',
	FOOD_V_BUG		= 'COOKINGPRODUCTS/PRODUCT.R.BUG.DDS',
	FOOD_V_GEK		= 'COOKINGPRODUCTS/PRODUCT.MILK.PROTO.DDS',
	FOOD_V_FLYER	= 'COOKINGPRODUCTS/PRODUCT.MILK.CRAW.DDS',
	FOOD_V_MILK		= 'COOKINGPRODUCTS/PRODUCT.MILK.WILD.DDS',
	FOOD_V_PCAT		= 'COOKINGPRODUCTS/PRODUCT.HONEY.WHITE.DDS',
	FOOD_R_BONEMILK	= 'COOKINGPRODUCTS/PRODUCT.MILK.BONE.DDS',
	FOOD_R_EYEBALLS	= 'COOKINGPRODUCTS/PRODUCT.R.EYEBALLS.DDS',
	FOOD_R_HONEY	= 'COOKINGPRODUCTS/PRODUCT.HONEY.BLUE.DDS',
	FOOD_R_HORROR	= 'COOKINGPRODUCTS/PRODUCT.R.HORROR.DDS',
	FOOD_V_BONE		= 'COOKINGPRODUCTS/PRODUCT.BONE.PIECE.DDS',
	FOOD_V_CAT		= 'COOKINGPRODUCTS/PRODUCT.MEAT.KIDNEY.DDS',
	FOOD_V_CRAB		= 'COOKINGPRODUCTS/PRODUCT.BONE.CRAB.DDS',
	FOOD_V_DIPLO	= 'COOKINGPRODUCTS/PRODUCT.EGG.GIANT.DDS',
	FOOD_V_ROBOT	= 'COOKINGPRODUCTS/PRODUCT.ROBOT.WIRE.DDS',
	FOOD_V_STRIDER	= 'COOKINGPRODUCTS/PRODUCT.EGG.TALL.DDS',
	FOOD_W_CASE		= 'COOKINGPRODUCTS/PRODUCT.MEAT.DDS',
	FOOD_MEAT_STEW	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_ORGAN_STEW	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_BONE	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_DRILL	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_BEET	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_DIG	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_BALL	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_BUG	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_EVIL	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_O_CH	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_M_CH	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_O_CR	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_M_CR	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_O_HOT	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_M_HOT	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_O_VEG	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_STEW_M_VEG	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	FOOD_R_EYESTEW	= 'COOKINGPRODUCTS/PRODUCT.REFINED.EVILSTEW.DDS',
	GEODE_CAVE		= 'U4PRODUCTS/PRODUCT.GEODECAVE.DDS',
	SHIPCHARGE		= 'U4PRODUCTS/PRODUCT.SHIPCHARGE.DDS',
	SIGNALCHARGE	= 'U4PRODUCTS/PRODUCT.POWERSURGE.DDS',
}

local mod_path	= 'D:/MODZ_stuff/NoMansSky/Published/Product Icons/_MOD.lMonk.Product Icons'
local dds_trg	= 'textures/ui/frontend/icons'

dofile('../LIB/_lua_2_mxml.lua')

local function WriteExmlFile(path, data, template)
	local function PathSplit(p)
		return {p:gsub('/', '\\'):match('^(.-)([^\\/]-)(%.[^.]-)$')}
	end
	os.execute(('if not exist "<>" md "<>"'):gsub('<>', PathSplit(path)[1]))
	local w_src = io.open(path, 'w')
	w_src:write(ToMxmlFile(data, template))
	w_src:close()

	print(('File %s.exml created.'):format(PathSplit(path)[2]))
end

local gc_prod = { meta = {name='Table'} }
for id, icon in pairs(prod_icons) do
	gc_prod[#gc_prod+1] = {
		meta = {name='Table', value='GcProductData', _id=id},
		ID = id,
		Icon = {
			meta = {name='Icon', value='TkTextureResource'},
			Filename = dds_trg:upper()..'/'..icon
		}
	}
end

WriteExmlFile(
	mod_path..'/METADATA/REALITY/TABLES/NMS_REALITY_GCPRODUCTTABLE.EXML',
	gc_prod,
	'cGcProductTable'
)

--- copy icons ----------------------------------------------------------------
local function lsh(p) return p:gsub('/', '\\') end
os.execute(
	('robocopy "%s" "%s\\%s" /S /XD %s /XF %s'):format(
		lsh('D:/MODZ_stuff/NoMansSky/Sources/_Textures_mod_source/textures/ui/frontend/icons'),
		lsh(mod_path),
		lsh(dds_trg),
		'buildable categories missions quickmenu technology u4substances',	-- exclude folders
		'_MY*'																-- exclude files
	)
)

print('Product Icons Mod Created.')
