--------------------------------------------------------------------------
local mod_desc = [[
  Building placement density reduction
  Enable continents
  (list pulled from BIOMEFILENAMES.MBIN)
]]------------------------------------------------------------------------

local building_density_mod = { -- BuildingClassEnum
	Shelter						= -3,
	Abandoned					= -1,
	Terminal					= -1,
	Shop						= -1,
	Outpost						= -0.2,
	Waypoint					= -2,
	Beacon						= -3,
	RadioTower					= -1,
	Observatory					= -1,
	Depot						= -1,
	Factory						= -2,
	Harvester					= -0.2,
	Plaque						= -2,
	Monolith					= -1,
	Portal						= 0,
	Ruin						= -0.2,
	Debris						= -1,
	DamagedMachine				= -2,
	DistressSignal				= -0.2,
	LandingPad					= 0,
	Base						= 0,
	MissionTower				= -1,
	CrashedFreighter			= -0.2,
	GraveInCave					= -0.2,
	StoryGlitch					= 0,
	TreasureRuins				= -0.2,
	GameStartSpawn				= 0,
	WaterCrashedFreighter		= -0.2,
	WaterTreasureRuins			= -0.2,
	WaterAbandoned				= -1,
	WaterDistressSignal			= -0.2,
	NPCDistressSignal			= -0.2,
	NPCDebris					= -0.2,
	LargeBuilding				= -0.2,
	Settlement_Hub				= 0,
	Settlement_LandingZone		= 0,
	Settlement_Bar				= 0,
	Settlement_Tower			= 0,
	Settlement_Market			= 0,
	Settlement_Small			= 0,
	Settlement_SmallIndustrial	= 0,
	Settlement_Medium			= 0,
	Settlement_Large			= 0,
	Settlement_Monument			= 0,
	Settlement_SheriffsOffice	= 0,
	Settlement_Double			= 0,
	Settlement_Farm				= 0,
	Settlement_Factory			= 0,
	Settlement_Clump			= 0,
	DroneHive					= 0,
	SentinelDistressSignal		= -0.4,
	AbandonedRobotCamp			= -0.2,
	RobotHead					= 0,
	DigSite						= 0,
	AncientGuardian				= 0,
	Settlement_Hub_Builders		= 0,
	Settlement_FishPond			= 0,
	Settlement_Builders_RoboArm	= 0,
	CargoDrop					= 0,
	ScrapYard					= 0
}
local mx_ct = {}
for build, mod in pairs(building_density_mod) do
	if not build:find('Water') then
		mx_ct[#mx_ct+1] = {
			PRECEDING_KEY_WORDS	= {'BuildingPlacement', build},
			VALUE_CHANGE_TABLE 	= {
				{'MinHeight',		120},
				{'WaterPlacement',	'Underwater'}
			}
		}
	end
	if mod ~= 0 then
		mx_ct[#mx_ct+1] = {
			MATH_OPERATION 		= '+',
			PRECEDING_KEY_WORDS	= {'BuildingPlacement', build, 'Density'},
			VALUE_CHANGE_TABLE 	= {
				{'Full',		mod},
				{'HalfWeird',	mod / 3}
			}
		}
	end
end

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 			= '+ META biome continental buildings',
	MOD_AUTHOR				= 'lMonk',
	NMS_VERSION				= '6.24',
	MOD_DESCRIPTION			= mod_desc,
	MODIFICATIONS 			= {{
	MBIN_CHANGE_TABLE		= {
	{--	|building placement| density reduction
		MBIN_FILE_SOURCE	= 'METADATA/SIMULATION/ENVIRONMENT/PLANETBUILDINGTABLE.MBIN',
		EXML_CREATE			= false,
		MXML_CHANGE_TABLE	= mx_ct
	},
	{--	enable |continents|
		MBIN_FILE_SOURCE	= {
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENBIGPROPSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENCORALBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENHIVESBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENHQBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENINFESTEDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENOCEANBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENPEACOCKBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENROCKYBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENROCKYWEIRDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENRUINSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BURNT/BURNTBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BURNT/BURNTREMIX/BURNTREMIXBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/DEAD/DEADBIGPROPSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/DEAD/DEADBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/DEAD/DEADFROZENBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/DEAD/DEADFROZENWEIRDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/DEAD/DEADWATERBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/DESOLATE/DESOLATEBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FLORAL/FLORALBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENBIGPROPSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENHQBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENINFESTEDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENISLANDSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENPILLARBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENROCKYBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENROCKYWEIRDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENRUINSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/GASGIANTS/GASGIANTSTANDARDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGELUSH/HUGELUSHBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGERING/HUGERINGBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEROCK/HUGEROCKBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGESCORCHED/HUGESCORCHBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGETOXIC/HUGETOXICBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/HUGEPROPS/HUGEUWPLANT/HUGEUVWPLANTBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/IRRADIATED/IRRADIATEDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/IRRADIATED/IRRADREMIX/IRRADREMIXBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/JUNGLE/JUNGLEBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LAVA/LAVABIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LAVA/LAVAISLANDSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHBIGPROPSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHBUBBLESBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHHQBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHHQTENTACLEBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHINFESTEDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHROCKYBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHROCKYWEIRDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHROOMABIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHROOMBBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHRUINSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHULTRABIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/NOXIOUS/NOXIOUSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/NOXIOUS/NOXREMIX/NOXREMIXBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVEBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVEGLOWBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVEISLANDSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVERUINSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVEVARIANTBBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOBIGPROPSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOINFESTEDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOSPIKECRYSTALSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHBIGPROPSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHCORALBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHEDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHEDRUINSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHEDSHIELDTREEBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHINFESTEDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHOCEANBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SUBZERO/SUBZEROBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SUBZERO/SUBZREMIX/SUBZREMIXBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SWAMP/SWAMPBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SWAMP/SWAMPISLANDSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICBIGPROPSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICEGGSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICINFESTEDBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICISLANDSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICOCEANBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICROCKYBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICRUINSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICSPORESBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICTENTACLESBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/BEAMSTONE/BEAMSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/BONESPIRE/BONESPIREBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/CONTOUR/CONTOURBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/ELBUBBLE/ELBUBBLEBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/FRACTALCUBE/FRACTCUBEBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/HEXAGON/HEXAGONBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/HOUDINIPROPS/HOUDINIPROPSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/HYDROGARDEN/HYDROGARDENBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/IRRISHELLS/IRRISHELLSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/MSTRUCTURES/MSTRUCTBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/SHARDS/SHARDSBIOME.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/WIRECELLS/WIRECELLSBIOME.MBIN',
		},
		EXML_CREATE			= false,
		MXML_CHANGE_TABLE	= {
			{
				VALUE_CHANGE_TABLE 	= {
					{'Continent', 1},
					{'ForceContinentalNoise', true}
				}
			}
		}
	}
}}}}
