--[[┎──────────────────────────────────────────
	┃ 		ALWAYS EXCLUDED FROM BATCH
	┠──────────────────────────────────────────
	┃ 			LOD levels increase
────┸──────────────────────────────────────--]]
Path = 'METADATA\SIMULATION\SOLARSYSTEM\BIOMES\\'

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 		= '_META LOD increase.pak',
	MOD_AUTHOR			= 'lMonk',
	NMS_VERSION			= '3.42',
	MOD_BATCHNAME		= '_META ~@~collection.pak',
	MODIFICATIONS 		= {{
	MBIN_CHANGE_TABLE	= {
	{
		MBIN_FILE_SOURCE	= {
			Path..'BARREN\ULTRAOBJECTS\BARRENHQOBJECTSFULLULTRA.MBIN',
			Path..'BARREN\ULTRAOBJECTS\BARRENOBJECTSFULLULTRA.MBIN',
			Path..'BARREN\BARRENBIGPROPSOBJECTSFULL.MBIN',
			Path..'BARREN\BARRENCORALOBJECTS.MBIN',
			Path..'BARREN\BARRENHIVESOBJECTS.MBIN',
			Path..'BARREN\BARRENHQOBJECTSFULL.MBIN',
			Path..'BARREN\BARRENINFESTEDOBJECTS.MBIN',
			Path..'BARREN\BARRENOBJECTSDEAD.MBIN',
			Path..'BARREN\BARRENOBJECTSFULL.MBIN',
			Path..'BARREN\BARRENOBJECTSLOW.MBIN',
			Path..'BARREN\BARRENOBJECTSMID.MBIN',
			Path..'BARREN\BARRENROCKYOBJECTS.MBIN',
			Path..'BARREN\BARRENROCKYWEIRDOBJECTS.MBIN',

			Path..'CAVE\CAVEBIOMEDEAD.MBIN',
			Path..'CAVE\CAVEBIOMEEMPTY.MBIN',
			Path..'CAVE\CAVEBIOMEFULL.MBIN',
			Path..'CAVE\CAVEBIOMEGRASSBUSHES.MBIN',
			Path..'CAVE\CAVEBIOMEMID.MBIN',
			Path..'CAVE\CAVEBIOMESPARSETOXIC.MBIN',

			Path..'DEAD\DEADBIGPROPSOBJECTSFULL.MBIN',
			Path..'DEAD\DEADBIGPROPSOBJECTSVAR1.MBIN',
			Path..'DEAD\DEADBIGPROPSOBJECTSVAR2.MBIN',
			Path..'DEAD\DEADBIGPROPSOBJECTSVAR3.MBIN',
			Path..'DEAD\DEADOBJECTSDEAD.MBIN',
			Path..'DEAD\FROZENDEADOBJECTS.MBIN',
			Path..'DEAD\FROZENDEADWEIRDOBJECTS.MBIN',

			Path..'HUGEPROPS\HUGELUSH\HUGELUSHOBJECTSFULL.MBIN',
			Path..'HUGEPROPS\HUGERING\HUGERINGOBJECTSFULL.MBIN',
			Path..'HUGEPROPS\HUGEROCK\HUGEROCKOBJECTSFULL.MBIN',
			Path..'HUGEPROPS\HUGESCORCHED\HUGESCORCHOBJECTSFULL.MBIN',
			Path..'HUGEPROPS\HUGETOXIC\HUGETOXICOBJECTSFULL.MBIN',
			Path..'HUGEPROPS\HUGEUWPLANT\HUGEUWPLANTOBJECTS.MBIN',

			Path..'FROZEN\ULTRAOBJECTS\FROZENOBJECTSFULLULTRA.MBIN',
			Path..'FROZEN\FROZENBIGPROPSOBJECTSFULL.MBIN',
			Path..'FROZEN\FROZENHQOBJECTSMID.MBIN',
			Path..'FROZEN\FROZENOBJECTSDEAD.MBIN',
			Path..'FROZEN\FROZENOBJECTSFULL.MBIN',
			Path..'FROZEN\FROZENOBJECTSLOW.MBIN',
			Path..'FROZEN\FROZENOBJECTSMID.MBIN',
			Path..'FROZEN\FROZENPILLAROBJECTS.MBIN',
			Path..'FROZEN\FROZENROCKYOBJECTS.MBIN',
			Path..'FROZEN\FROZENROCKYWEIRDOBJECTS.MBIN',

			Path..'LAVA\LAVAOBJECTSFULL.MBIN',

			Path..'LUSH\LUSHBIGPROPSOBJECTSFULL.MBIN',
			Path..'LUSH\LUSHHQOBJECTSFULLULTRA.MBIN',
			Path..'LUSH\LUSHHQTENTACLEOBJECTSFULL.MBIN',
			Path..'LUSH\LUSHINFESTEDOBJECTS.MBIN',
			Path..'LUSH\LUSHOBJECTSFULLULTRA.MBIN',
			Path..'LUSH\LUSHROCKYOBJECTS.MBIN',
			Path..'LUSH\LUSHROCKYWEIRDOBJECTS.MBIN',
			Path..'LUSH\LUSHROOMAOBJECTS.MBIN',
			Path..'LUSH\LUSHROOMBOBJECTS.MBIN',
			Path..'LUSH\LUSHULTRAOBJECTS.MBIN',
			Path..'LUSH\ULTRAEXTERNALOBJECTS.MBIN',
			Path..'LUSH\LUSHHQOBJECTSFULL.MBIN',
			Path..'LUSH\LUSHOBJECTSDEAD.MBIN',
			Path..'LUSH\LUSHOBJECTSFULL.MBIN',
			Path..'LUSH\LUSHOBJECTSLOW.MBIN',
			Path..'LUSH\LUSHOBJECTSMID.MBIN',

			Path..'RADIOACTIVE\ULTRAOBJECTS\RADIOACTIVEOBJECTSFULLULTRA.MBIN',
			Path..'RADIOACTIVE\RADIOACTIVEALIENOBJECTS.MBIN',
			Path..'RADIOACTIVE\RADIOACTIVEGLOWOBJECTS.MBIN',
			Path..'RADIOACTIVE\RADIOACTIVEOBJECTSDEAD.MBIN',
			Path..'RADIOACTIVE\RADIOACTIVEOBJECTSFULL.MBIN',
			Path..'RADIOACTIVE\RADIOACTIVEOBJECTSLOW.MBIN',
			Path..'RADIOACTIVE\RADIOACTIVEOBJECTSMID.MBIN',
			Path..'RADIOACTIVE\RADIOBIGPROPSOBJECTS.MBIN',
			Path..'RADIOACTIVE\RADIOSPIKECRYSTALSOBJECTS.MBIN',
			Path..'RADIOACTIVE\RADIOSPIKEPOTATOOBJECTS.MBIN',

			Path..'SCORCHED\ULTRAOBJECTS\SCORCHEDOBJECTSFULLULTRA.MBIN',
			Path..'SCORCHED\SCORCHBIGPROPSOBJECTSFULL.MBIN',
			Path..'SCORCHED\SCORCHCORALOBJECTS.MBIN',
			Path..'SCORCHED\SCORCHEDALIENOBJECTS.MBIN',
			Path..'SCORCHED\SCORCHEDOBJECTSDEAD.MBIN',
			Path..'SCORCHED\SCORCHEDOBJECTSFULL.MBIN',
			Path..'SCORCHED\SCORCHEDOBJECTSLOW.MBIN',
			Path..'SCORCHED\SCORCHEDOBJECTSMID.MBIN',
			Path..'SCORCHED\SCORCHEDSHIELDTREEOBJECTS.MBIN',

			Path..'SWAMP\SWAMPOBJECTSFULL.MBIN',

			Path..'TOXIC\ULTRAOBJECTS\TOXICOBJECTSFULLULTRA.MBIN',
			Path..'TOXIC\TOXICBIGPROPSOBJECTSFULL.MBIN',
			Path..'TOXIC\TOXICEGGSMOONOBJECTS.MBIN',
			Path..'TOXIC\TOXICEGGSOBJECTS.MBIN',
			Path..'TOXIC\TOXICINFESTEDOBJECTS.MBIN',
			Path..'TOXIC\TOXICOBJECTSDEAD.MBIN',
			Path..'TOXIC\TOXICOBJECTSFULL.MBIN',
			Path..'TOXIC\TOXICOBJECTSLOW.MBIN',
			Path..'TOXIC\TOXICOBJECTSMID.MBIN',
			Path..'TOXIC\TOXICSPORESOBJECTS.MBIN',
			Path..'TOXIC\TOXICTENTACLESOBJECTS.MBIN',

			Path..'UNDERWATER\UNDERWATERCRYSTALS.MBIN',
			Path..'UNDERWATER\UNDERWATERCUCUMBERLIGHTS.MBIN',
			Path..'UNDERWATER\UNDERWATERCURVECORAL.MBIN',
			Path..'UNDERWATER\UNDERWATERDEAD.MBIN',
			Path..'UNDERWATER\UNDERWATERFULL.MBIN',
			Path..'UNDERWATER\UNDERWATERGASBAGS.MBIN',
			Path..'UNDERWATER\UNDERWATERMID.MBIN',
			Path..'UNDERWATER\UNDERWATERMONOLITHS.MBIN',
			Path..'UNDERWATER\UNDERWATERPLANT.MBIN',

			Path..'WEIRD\BEAMSTONE\BEAMSOBJECTSDEAD.MBIN',
			Path..'WEIRD\BONESPIRE\BONESPIREOBJECTSDEAD.MBIN',
			Path..'WEIRD\CONTOUR\CONTOUROBJECTSDEAD.MBIN',
			Path..'WEIRD\ELBUBBLE\ELBUBBLEOBJECTSDEAD.MBIN',
			Path..'WEIRD\FRACTALCUBE\FRACTCUBEOBJECTSDEAD.MBIN',
			Path..'WEIRD\HEXAGON\HEXAGONOBJECTSDEAD.MBIN',
			Path..'WEIRD\HYDROGARDEN\HYDROGARDENOBJECTSDEAD.MBIN',
			Path..'WEIRD\IRRISHELLS\IRRISHELLSOBJECTSDEAD.MBIN',
			Path..'WEIRD\MSTRUCTURES\MSTRUCTOBJECTSDEAD.MBIN',
			Path..'WEIRD\SHARDS\SHARDSOBJECTSDEAD.MBIN',
			Path..'WEIRD\WIRECELLS\WIRECELLSOBJECTSDEAD.MBIN',
		},
		EXML_CHANGE_TABLE	= {
			{
				REPLACE_TYPE 		= 'ALL',
				VALUE_MATCH_TYPE 	= 'NUMBER',
				VALUE_MATCH			= 200,
				VALUE_MATCH_OPTIONS = '<',
				MATH_OPERATION 		= '*',
				PRECEDING_KEY_WORDS = 'LodDistances',
				VALUE_CHANGE_TABLE 	= {
					{'IGNORE',		2} -- 3
				}
			},
			{
				REPLACE_TYPE 		= 'ALL',
				VALUE_MATCH_TYPE 	= 'NUMBER',
				VALUE_MATCH			= 460,
				VALUE_MATCH_OPTIONS = '>',
				MATH_OPERATION 		= '*',
				PRECEDING_KEY_WORDS = 'LodDistances',
				VALUE_CHANGE_TABLE 	= {
					{'IGNORE',		1.4} -- 1.6
				}
			},
			-- {
			-- 	REPLACE_TYPE 		= 'ALL',
			-- 	VALUE_MATCH_TYPE 	= 'NUMBER',
			-- 	VALUE_MATCH			= 8,
			-- 	VALUE_MATCH_OPTIONS = '<',
			-- 	MATH_OPERATION 		= '+',
			-- 	VALUE_CHANGE_TABLE 	= {
			-- 		{'MaxRegionRadius',	2} -- not found in ~30 of the files. Results in a warning.
			-- 	}
			-- },
			-- {
			-- 	REPLACE_TYPE 		= 'ALL',
			-- 	VALUE_MATCH_TYPE 	= 'NUMBER',
			-- 	VALUE_MATCH			= 9000,
			-- 	VALUE_MATCH_OPTIONS = '<',
			-- 	MATH_OPERATION 		= '*',
			-- 	VALUE_CHANGE_TABLE 	= {
			-- 		{'FadeInStartDistance',		1.5}, -- 2
			-- 		{'FadeInEndDistance',		1.5},
			-- 		{'FadeOutStartDistance',	1.5},
			-- 		{'FadeOutEndDistance',		1.5}
			-- 	}
			-- }
		}
	}
}}}}
