
local entity_list = {
	'D:/MODZ_stuff/NoMansSky/UNPACKED/MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/COMMONPARTS/ABANDONEDTERMINAL.SCENE.MXML',
	'D:/MODZ_stuff/NoMansSky/UNPACKED/MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/SPACEBASE/ABANFRIGATETERMINALAIRLOCK.SCENE.MXML',
	'D:/MODZ_stuff/NoMansSky/UNPACKED/MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/SPACEBASE/ABANFRIGATETERMINALAIRLOCKRED.SCENE.MXML',
	'D:/MODZ_stuff/NoMansSky/UNPACKED/MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/SPACEBASE/ABANFRIGATETERMINALCAPTAIN.SCENE.MXML',
	'D:/MODZ_stuff/NoMansSky/UNPACKED/MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/FREIGHTERBASE/CORRIDOR/A/PARTS/XSHAPE0_LOD.SCENE.MXML',
	'D:/MODZ_stuff/NoMansSky/UNPACKED/MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/FREIGHTERBASE/CORRIDOR/A_GLASS/PARTS/XSHAPE0_LOD.SCENE.MXML',
	'D:/MODZ_stuff/NoMansSky/UNPACKED/MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/FREIGHTERBASE/WALKWAY/A/PARTS/XSHAPE0_LOD.SCENE.MXML',
	'D:/MODZ_stuff/NoMansSky/UNPACKED/MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/FREIGHTERBASE/CORRIDOR/A/PARTS/XSHAPE0_NAV.SCENE.MXML',
	'D:/MODZ_stuff/NoMansSky/UNPACKED/MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/PARTS/BUILDABLEPARTS/FREIGHTERBASE/WALKWAY/A/PARTS/XSHAPE0_NAV.SCENE.MXML',
}

-- get LodDistances    :: '<Property name="LodDistances">(.-)</Property>'
-- get collision types :: '"Type" value="COLLISION".-"Name" value="TYPE".-"Value" value="(.-)"'

local pattern = '"Type" value="COLLISION".-"Name" value="TYPE".-"Value" value="(.-)"'

for _,f in ipairs(entity_list) do
	local r_src = io.open(f, 'r')
	local chunk = r_src:read('a')
    for sect in chunk:gmatch(pattern) do
		if sect ~= 'Mesh' then
			print(f..'\n'..sect..'\n')
		end
	end
	r_src:close()
end
