------------------------------------------------------------
NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 		= '+  ALL random palettes',
	MOD_AUTHOR			= 'lMonk',
	NMS_VERSION			= '6.06',
	MODIFICATIONS 		= {{
	MBIN_CHANGE_TABLE	= {
	{
		MBIN_FILE_SOURCE = {
			-- biome
			'METADATA/SIMULATION/SOLARSYSTEM/COLOURS/BASECOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BARREN/BARRENHQCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BURNT/BURNTCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/DEAD/DEADCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/DESOLATE/DESOLATECOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENHQCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/IRRADIATED/IRRADIATEDCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LAVA/LAVACOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHBUBBLESCOLOURPALETTE.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHHQCOLOURPALETTE.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHROOMACOLOURPALETTE.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHROOMBCOLOURPALETTE.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/LUSH/LUSHULTRACOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/NOXIOUS/NOXIOUSCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SCORCHED/SCORCHCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SUBZERO/SUBZEROCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/SWAMP/SWAMPCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICEGGSCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICSPORESCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/TOXIC/TOXICTENTACLESCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/BEAMSTONE/BEAMSCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/BONESPIRE/BONESPIRECOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/CONTOUR/CONTOURCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/ELBUBBLE/ELBUBBLECOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/FRACTALCUBE/FRACTCUBECOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/HEXAGON/HEXAGONCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/HOUDINIPROPS/HOUDINIPROPSCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/HYDROGARDEN/HYDROGARDENCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/IRRISHELLS/IRRISHELLSCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/MSTRUCTURES/MSTRUCTCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/SHARDS/SHARDSCOLOURPALETTES.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/WEIRD/WIRECELLS/WIRECELLSCOLOURPALETTES.MBIN',
			-- space
			'METADATA/SIMULATION/SOLARSYSTEM/WEATHER/SKYSETTINGS/SPACESKYCOLOURS.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/WEATHER/SKYSETTINGS/SPACERARESKYCOLOURS.MBIN',
			-- sky
			'METADATA/SIMULATION/SOLARSYSTEM/WEATHER/SKYSETTINGS/DAYSKYCOLOURS.MBIN',
			'METADATA/SIMULATION/SOLARSYSTEM/WEATHER/SKYSETTINGS/NIGHTSKYCOLOURS.MBIN',
			-- water
			'METADATA/SIMULATION/SOLARSYSTEM/COLOURS/WATERCOLOURS.MBIN',
		},
		MXML_CHANGE_TABLE	= {
			{
				REPLACE_TYPE 		= 'All',
				VALUE_CHANGE_TABLE 	= {
					{'R', math.random()},
					{'G', math.random()},
					{'B', math.random()}
				}
			}
		}
	}
}}}}
