--[[┎──────────────────────────────────────────────────────────────
	┃ dropship remove contrails
────┸──────────────────────────────────────────────────────────--]]
function BuildExmlChangeTable_DeleteContrail(lst)
	local T = {}
	for i = 1, #lst do
		local section = {
			SPECIAL_KEY_WORDS	= {'Name', 'Contrail' .. lst[i]},
			REMOVE				= 'SECTION'
		}
		table.insert(T, section)
	end
	return T
end

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 		= '__MODEL dropship remove contrails.pak',
	MOD_AUTHOR			= 'lMonk',
	NMS_VERSION			= '3.22',
	MOD_BATCHNAME		= '_MODELS ~@~collection.pak',
	MOD_DESCRIPTION		= 'U',
	MODIFICATIONS 		= {{
	MBIN_CHANGE_TABLE	= {
	{
		MBIN_FILE_SOURCE	= {
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSA\SUBWINGSA_LEFT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSA\SUBWINGSA_RIGHT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSE\SUBWINGSE_LEFT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSE\SUBWINGSE_RIGHT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSI\SUBWINGSI_LEFT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSI\SUBWINGSI_RIGHT.SCENE.MBIN',
		},
		EXML_CHANGE_TABLE	= BuildExmlChangeTable_DeleteContrail({''})
	},
	{
		MBIN_FILE_SOURCE	= {
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSB\SUBWINGSB_LEFT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSB\SUBWINGSB_RIGHT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSC\SUBWINGSC_LEFT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSC\SUBWINGSC_RIGHT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSD\SUBWINGSD_LEFT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSD\SUBWINGSD_RIGHT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSF\SUBWINGSF_LEFT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSF\SUBWINGSF_RIGHT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSG\SUBWINGSG_LEFT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSG\SUBWINGSG_RIGHT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSH\SUBWINGSH_LEFT.SCENE.MBIN',
			'MODELS\COMMON\SPACECRAFT\DROPSHIPS\SUBWINGS\SUBWINGSH\SUBWINGSH_RIGHT.SCENE.MBIN',
		},
		EXML_CHANGE_TABLE	= BuildExmlChangeTable_DeleteContrail({'', 1})
	}
}}}}
