-------------------------------------------------------------------

local biome_objects = {
	'MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMPLANT.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SNOWFRAGMENTS.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/BARREN/HQ/FOLIAGE/BARRENGRASSLARGE.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/FRAGMENTS.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKS.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/COMMON/ROCKS/SURFACEBLEND/GRAVELPATCHSNOWBLEND.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/COMMON/FLOWERS/YARROW.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREEBARE.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGETREE.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/COMMON/GRASS/TALLGRASSBILLBOARD.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/BARREN/HQ/SMALLROCK.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/COMMON/ROCKS/SMALL/SMALLROCK.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/HQFROZEN/FOLIAGE/FROZENBUSHYGRASS.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLROCKSSHARDS.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/FROZEN/LARGEPROPS/LARGEROCKS.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/COMMON/GRASS/NEWCROSSGRASS.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/FROZEN/SMALLPROPS/SMALLPLANT.SCENE.MBIN',
	'MODELS/PLANETS/BIOMES/COMMON/PLANTS/SPRIGBUSH.SCENE.MBIN',
}

_modifier = nil
function MathOpSelect(property, currentValue)
	currentValue = tonumber(currentValue)
	if currentValue ~= 0 then
		print(string.format('%s = %s * %s -- %s', currentValue * _modifier, currentValue, _modifier, property))
		return currentValue * _modifier
	else
		print(string.format('%s = %s + %s -- %s', currentValue + _modifier, currentValue, _modifier, property))
		return currentValue + _modifier
	end
end

function CalcDensities()
	local T = {}
	local tm = {}
	for _, mbin in ipairs(biome_objects) do
		idx = #T + 1
		T[idx] = {
			REPLACE_TYPE 		= 'All',
			INTEGER_TO_FLOAT	= 'Force',
			SPECIAL_KEY_WORDS	= {'Filename', mbin},
			SECTION_UP			= 1,
			VALUE_CHANGE_TABLE 	= {}
		}
		if mbin:find('TREE') then
			T[idx].VALUE_CHANGE_TABLE = 0 -- ...
		end


	end
end

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 		= '___TEST 09 inline function.pak',
	MOD_AUTHOR			= 'lMonk',
	NMS_VERSION			= '4.38',
	MODIFICATIONS 		= {{
	MBIN_CHANGE_TABLE	= {
	{
		MBIN_FILE_SOURCE	= 'METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENOBJECTSFULL.MBIN',
		EXML_CHANGE_TABLE	= {
			{
				-- MATH_OPERATION 		= '*',
				SPECIAL_KEY_WORDS	= {'Name', 'INTENSITY'},
				VALUE_CHANGE_TABLE 	= {
					{'SlopeDensity', 		9000}
				}
			}
		}
	},
}}}}
