-----------------------------------------------------------------
mod_desc = [[
  - dropship: subwing_F dim lights; left subwing_F decal fix;
   subwing_E delete big decal; hull decals re-aligned
  - No foggy headlights cone on cockpits
]]---------------------------------------------------------------

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 			= '__SHIP dropship.pak',
	MOD_AUTHOR				= 'lMonk',
	NMS_VERSION				= '4.44',
	MOD_DESCRIPTION			= mod_desc,
	GLOBAL_INTEGER_TO_FLOAT = 'Force',
	MODIFICATIONS 			= {{
	MBIN_CHANGE_TABLE		= {
	{--	dropship |subwing_F dim lights|
		MBIN_FILE_SOURCE	= {
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSF/SUBWINGSF_LEFT.SCENE.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSF/SUBWINGSF_RIGHT.SCENE.MBIN',
		},
		EXML_CHANGE_TABLE	= {
			{
				SPECIAL_KEY_WORDS	= {'Name', 'Glow'},
				VALUE_CHANGE_TABLE 	= {
					{'TransY',		0},		-- -0.05168
					{'ScaleY',		0.42}
				}
			},
			{
				SPECIAL_KEY_WORDS 	= {
					{'Name', 'pointLight1', 'Name', 'INTENSITY'},
					{'Name', 'pointLight2', 'Name', 'INTENSITY'}
				},
				VALUE_CHANGE_TABLE 	= {
					{'Value',		26000}
				}
			}
		}
	},
	{--	|dropship left subwing_F decal fix|
		MBIN_FILE_SOURCE	= 'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSF/SUBWINGSF_LEFT.SCENE.MBIN',
		EXML_CHANGE_TABLE	= {
			{
				SPECIAL_KEY_WORDS	= {'Name', '_Rectangle_A'},
				VALUE_CHANGE_TABLE 	= {
					{'RotX',		-59.0957},
					{'RotY',		90}
				}
			},
			{
				SPECIAL_KEY_WORDS	= {'Name', '_Letter_A'},
				VALUE_CHANGE_TABLE 	= {
					{'RotX',		-60.32834},
					{'RotY',		90}
				}
			}
		}
	},
	{--	|no foggy headlights| cone from cockpits
		MBIN_FILE_SOURCE	= {
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/COCKPIT/COCKPITA.SCENE.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/COCKPIT/COCKPITB.SCENE.MBIN',
		},
		EXML_CHANGE_TABLE	= {
			{
				REPLACE_TYPE 		= 'All',
				SPECIAL_KEY_WORDS	= {'Type', 'LIGHT'},
				REMOVE				= 'Section'
			}
		}
	},
	{--	|glow parts bluewhite|
		MBIN_FILE_SOURCE	= {
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/COCKPIT/COCKPITA/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSC/SUBWINGSC_LEFT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSC/SUBWINGSC_RIGHT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSD/SUBWINGSD_LEFT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSD/SUBWINGSD_RIGHT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSE/SUBWINGSE_LEFT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSE/SUBWINGSE_LEFT/GLOW_MAT1.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSE/SUBWINGSE_RIGHT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSE/SUBWINGSE_RIGHT/GLOW_MAT1.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSF/SUBWINGSF_LEFT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSF/SUBWINGSF_LEFT/GLOW_MAT1.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSF/SUBWINGSF_RIGHT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSF/SUBWINGSF_RIGHT/GLOW_MAT1.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSG/SUBWINGSG_LEFT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSG/SUBWINGSG_RIGHT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSH/SUBWINGSH_LEFT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSH/SUBWINGSH_RIGHT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSI/SUBWINGSI_LEFT/GLOW_MAT.MATERIAL.MBIN',
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSI/SUBWINGSI_RIGHT/GLOW_MAT.MATERIAL.MBIN',
		},
		EXML_CHANGE_TABLE	= {
			{
				SPECIAL_KEY_WORDS	= {'Name', 'gMaterialColourVec4'},
				VALUE_CHANGE_TABLE 	= {
					{'x',			0.46},
					{'y',			0.62},
					{'z',			0.76}
				}
			}
		}
	},
	{--	dropship |subwing_E_L letter| decal
		MBIN_FILE_SOURCE	= {
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSE/SUBWINGSE_LEFT.SCENE.MBIN',
		},
		EXML_CHANGE_TABLE	= {
			{
				SPECIAL_KEY_WORDS	= {'Name', '_Letter_A'},
				VALUE_CHANGE_TABLE 	= {
					{'RotX',		-42.487},	-- 42.486935
					{'RotY',		90},		-- -90
				}
			}
		}
	},
	{--	dropship |subwing_E_R letter| decal
		MBIN_FILE_SOURCE	= {
			'MODELS/COMMON/SPACECRAFT/DROPSHIPS/SUBWINGS/SUBWINGSE/SUBWINGSE_RIGHT.SCENE.MBIN',
		},
		EXML_CHANGE_TABLE	= {
			{
				SPECIAL_KEY_WORDS	= {'Name', '_Letter_A'},
				VALUE_CHANGE_TABLE 	= {
					{'RotX',		42.487},	-- -42.486935
					{'RotY',		-90},		-- 90
				}
			}
		}
	},
	{--	|dropship hull decals| fix
		MBIN_FILE_SOURCE	= 'MODELS/COMMON/SPACECRAFT/DROPSHIPS/HULL/HULLA.SCENE.MBIN',
		EXML_CHANGE_TABLE	= {
			{
				SPECIAL_KEY_WORDS	= {'Name', '_SideL_A1'}, -- R horiz
				VALUE_CHANGE_TABLE 	= {
					{'TransX',		0},		-- 1.5 (+ to left)
					{'TransZ',		0.35},	-- 0.219
					{'RotX',		180},	-- 0
					{'RotY',		270},	-- -77.34
					{'ScaleX',		1.9},	-- 2.107
					{'ScaleY',		1.0},	-- 1.054
					{'ScaleZ',		3.79},	-- 0.638
				}
			},
			{
				SPECIAL_KEY_WORDS	= {'Name', '_SideL_A'}, -- L diagonal
				VALUE_CHANGE_TABLE 	= {
					{'TransX', 		0},		-- 1.36
					{'RotY',		90},	-- -90
					{'RotZ',		0},		-- -28.073
					{'ScaleX',		2.84},	-- 3.766
					{'ScaleY',		1.4},	-- 1.883
					{'ScaleZ',		3.79},	-- 1.14
				}
			},
			{
				SPECIAL_KEY_WORDS 	= {
					{'Name', '_SideL_A3'},	-- L horiz
					{'Name', '_SideR_A'},	-- R diagonal
				},
				REMOVE				= 'Section'
			}
		}
	}
}}}}
