--[[┎──────────────────────────────────────────────────────
	┃ shrink UI popup panels
────┸──────────────────────────────────────────────────--]]
--[[
UI\COMPONENTS\ACTIONBUTTON.MBIN
UI\COMPONENTS\EMPTYSLOTBUTTON.MBIN
UI\COMPONENTS\POPUPTAB.MBIN
UI\COMPONENTS\POPUPTABFRAME.MBIN
UI\COMPONENTS\POPUPTITLEWITHSUBTITLE.MBIN
UI\COMPONENTS\SUBSTANCEAMOUNT.MBIN
UI\COMPONENTS\SUBSTANCEAMOUNTBLANK.MBIN
UI\COMPONENTS\TECH\SUBSTANCEAMOUNTSECTION.MBIN
UI\COMPONENTS\TECH\TECHCHARGESECTION.MBIN
UI\COMPONENTS\TECH\TECHSTATBAR.MBIN
UI\COMPONENTS\TECH\TECHSTATSSECTION.MBIN
UI\SLOTS\SLOT_ITEM.MBIN
UI\POPUP_BUILD.MBIN
UI\POPUP_BUYSELL.MBIN
UI\POPUP_BUYSELLTECH.MBIN
UI\POPUP_EMPTYSLOT.MBIN
UI\POPUP_INVENTORY.MBIN
UI\POPUP_NEWTECHNOLOGY.MBIN
UI\POPUP_TECHNOLOGY.MBIN
--]]

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 		= '_TEST 07 small UI panels.pak',
	MOD_AUTHOR			= 'lMonk',
	NMS_VERSION			= '3.35',
	MOD_BATCHNAME		= '_UI ~@~collection.pak',
	MODIFICATIONS 		= {{
	MBIN_CHANGE_TABLE	= {
	{
		MBIN_FILE_SOURCE	= {
			'UI\POPUP_BUILD.MBIN',
			'UI\POPUP_BUYSELL.MBIN',
			'UI\POPUP_BUYSELLTECH.MBIN',
			'UI\POPUP_EMPTYSLOT.MBIN',
			'UI\POPUP_INVENTORY.MBIN',
			'UI\POPUP_NEWTECHNOLOGY.MBIN',
			'UI\POPUP_TECHNOLOGY.MBIN',
		},
		EXML_CHANGE_TABLE	= {
			{
				REPLACE_TYPE 		= 'ALL',
				VALUE_MATCH_TYPE 	= 'NUMBER',
				MATH_OPERATION 		= '+',
				VALUE_MATCH			= 27,
				VALUE_MATCH_OPTIONS = '>=',
				VALUE_CHANGE_TABLE 	= {
					{'FontHeight',	-6}
				}
			},
			{
				REPLACE_TYPE 		= 'ALL',
				VALUE_MATCH_TYPE 	= 'NUMBER',
				MATH_OPERATION 		= '+',
				VALUE_MATCH			= 25,
				VALUE_MATCH_OPTIONS = '<=',
				VALUE_CHANGE_TABLE 	= {
					{'FontHeight',	-4}
				}
			},
			{
				REPLACE_TYPE 		= 'ALL',
				VALUE_MATCH_TYPE 	= 'NUMBER',
				MATH_OPERATION 		= '+',
				VALUE_MATCH			= 28,
				VALUE_MATCH_OPTIONS = '>',
				VALUE_CHANGE_TABLE 	= {
					{'PaddingX',	-6}
				}
			},
			{
				REPLACE_TYPE 		= 'ALL',
				VALUE_MATCH_TYPE 	= 'NUMBER',
				MATH_OPERATION 		= '+',
				VALUE_MATCH			= 7,
				VALUE_MATCH_OPTIONS = '>',
				VALUE_CHANGE_TABLE 	= {
					{'PaddingY',	-2}
				}
			},
			{
				REPLACE_TYPE 		= 'ALL',
				VALUE_MATCH_TYPE 	= 'NUMBER',
				MATH_OPERATION 		= '+',
				VALUE_MATCH			= 24,
				VALUE_MATCH_OPTIONS = '=',
				VALUE_CHANGE_TABLE 	= {
					{'Width',		-4},
					{'Height',		-4}
				}
			},
			{
				REPLACE_TYPE 		= 'ALL',
				VALUE_MATCH_TYPE 	= 'NUMBER',
				MATH_OPERATION 		= '+',
				VALUE_MATCH			= 650,
				VALUE_MATCH_OPTIONS = '=',
				VALUE_CHANGE_TABLE 	= {
					{'Width',		-130}
				}
			},
			{
				VALUE_MATCH_TYPE 	= 'NUMBER',
				MATH_OPERATION 		= '+',
				VALUE_MATCH			= 1000,
				VALUE_MATCH_OPTIONS = '=',
				VALUE_CHANGE_TABLE 	= {
					{'Height',		-150}
				}
			},
		}
	}
}}}}
