--------------------------------------------------------------------
local mod_desc = [[
  - Remove settlement building class marker
  - Remove mists fog clouds
  - Remove space dust and plasma
  - varied rain and snow
  - Remove lines, include: HUD icons, trade routes, landing pad
  - Reduce space speed lines for thrust and pulse
  - Remove smoke and trails from mech and player
  - Remove contrails
]]-----------------------------------------------------------------

NMS_MOD_DEFINITION_CONTAINER = {
	MOD_FILENAME 			= '+ MODEL effects lines trails mist',
	MOD_AUTHOR				= 'lMonk',
	NMS_VERSION				= '6.24',
	MOD_DESCRIPTION			= mod_desc,
	MODIFICATIONS 			= {{
	MBIN_CHANGE_TABLE		= {
	{--	remove |settlement class marker|
		MBIN_FILE_SOURCE	= {
			'MODELS/EFFECTS/HOLOGRAM/BCLASSBUILDING.SCENE.MBIN',
			'MODELS/EFFECTS/HOLOGRAM/ACLASSBUILDING.SCENE.MBIN',
			'MODELS/EFFECTS/HOLOGRAM/SCLASSBUILDING.SCENE.MBIN',
		},
		MXML_CHANGE_TABLE	= {
			{
				PRECEDING_KEY_WORDS	= 'Children',
				REMOVE				= 'Section'
			}
		}
	},
	{--	|remove mists|
		MBIN_FILE_SOURCE	= {
		--	sentinel/ beacon/ droppod/ builder camp
			'MODELS/EFFECTS/DEBRIS/SENTINELSHIPCRASHMIST.SCENE.MBIN',
			'MODELS/EFFECTS/DEBRIS/ROBOTCAMPMIST.SCENE.MBIN',
		--	portal
			'MODELS/EFFECTS/PORTAL/PORTALCLOUDS.SCENE.MBIN',
		--	monolith/ plaque
			'MODELS/EFFECTS/RUINS/MONOLITHCLOUDS.SCENE.MBIN',
			'MODELS/EFFECTS/RUINS/PLAQUEAMBIENTMIST.SCENE.MBIN',
		--	abandoned
			'MODELS/EFFECTS/OUTPOST/ABANDONEDBUILDINGDOORMIST.SCENE.MBIN',
			'MODELS/EFFECTS/OUTPOST/ABANDONEDTRADERBUILDINGCORRIDOR.SCENE.MBIN',
			'MODELS/EFFECTS/OUTPOST/ABANDONEDTRADERBUILDINGDOORMIST.SCENE.MBIN',
			'MODELS/EFFECTS/OUTPOST/ABANDONEDWARRIORBUILDINGDOORMIST.SCENE.MBIN',
		--	nexus
			'MODELS/EFFECTS/NEXUS/BRIDGEVOLUMELIGHTSHAFTS.SCENE.MBIN',
			'MODELS/EFFECTS/NEXUS/LANDINGBAYMIST.SCENE.MBIN',
			'MODELS/EFFECTS/NEXUS/LEFTSIDEGROUNDMIST.SCENE.MBIN',
			'MODELS/EFFECTS/NEXUS/RIGHTSIDEGROUNDMIST.SCENE.MBIN',
			'MODELS/EFFECTS/NEXUS/SPIDERGROUNDMIST.SCENE.MBIN',
		--	space station
			'MODELS/EFFECTS/STATION/LARGEPADMIST.SCENE.MBIN',-- used in nexus corvette pad
			'MODELS/EFFECTS/STATION/GENERALFLOATINGSMOKE.SCENE.MBIN',
			'MODELS/EFFECTS/STATION/LAUNCHTUBEFILLMIST.SCENE.MBIN',
			'MODELS/EFFECTS/STATION/LAUNCHTUBEPIPESTEAM.SCENE.MBIN',
			'MODELS/EFFECTS/STATION/LAUNCHTUBESTEAM.SCENE.MBIN',
			'MODELS/EFFECTS/STATION/ENTRANCESMOKE.SCENE.MBIN',
			'MODELS/EFFECTS/STATION/LANDINGPADSMOKELOOP.SCENE.MBIN',
			'MODELS/EFFECTS/STATION/STATIONGROUNDMIST.SCENE.MBIN',
			'MODELS/EFFECTS/STATION/STATIONMIST.SCENE.MBIN',
		--	pirate station
			'MODELS/EFFECTS/STATION/PIRATEFLOORMIST.SCENE.MBIN',
			'MODELS/EFFECTS/STATION/PIRATEROOFMIST.SCENE.MBIN',
			'MODELS/EFFECTS/SMOKE/GENERALFLOORSMOKE.SCENE.MBIN',
		--	living frigate
			'MODELS/EFFECTS/SPACECRAFT/LIVINGFRIGATEATMOSPHERE.SCENE.MBIN',
		--	freighter bridge
			'MODELS/EFFECTS/SPACECRAFT/BRIDGEFLOORMIST.SCENE.MBIN',
		--	derelict freighter
			'MODELS/EFFECTS/ABANDONEDFREIGHTER/EXTERIORMAINDUST.SCENE.MBIN',
			'MODELS/EFFECTS/ABANDONEDFREIGHTER/SMOKECOLUMN.SCENE.MBIN',
			'MODELS/EFFECTS/ABANDONEDFREIGHTER/SMALLSMOKECOLUMN.SCENE.MBIN',
			'MODELS/EFFECTS/ABANDONEDFREIGHTER/ENTRANCESECTIONDEBRIS.SCENE.MBIN',
			'MODELS/EFFECTS/ABANDONEDFREIGHTER/ENTRANCESECTIONMIST.SCENE.MBIN',
			'MODELS/EFFECTS/ABANDONEDFREIGHTER/ENTRANCEDOORMIST.SCENE.MBIN',
			'MODELS/EFFECTS/ABANDONEDFREIGHTER/ENTRANCEFLOORMIST.SCENE.MBIN',
			'MODELS/EFFECTS/ABANDONEDFREIGHTER/ENTRANCEVOLUMELIGHT.SCENE.MBIN',
			'MODELS/EFFECTS/ABANDONEDFREIGHTER/ZEROGSPARKS.SCENE.MBIN',
			'MODELS/EFFECTS/HEAVYAIR/SPACE/ABANDONEDFREIGHTER.SCENE.MBIN',
		--	corvette
			'MODELS/EFFECTS/ABANDONEDFREIGHTER/AIRLOCKTUBEMIST.SCENE.MBIN',
		--	crashed freigher
			-- 'MODELS/EFFECTS/DEBRIS/CRASHEDFREIGHTERPLATFORMMIST.SCENE.MBIN',
			-- 'MODELS/EFFECTS/DEBRIS/CRASHEDFREIGHTERMIST.SCENE.MBIN',
			-- 'MODELS/EFFECTS/DEBRIS/CRASHEDFREIGHTERVENTSMOKE.SCENE.MBIN',
			-- 'MODELS/EFFECTS/DEBRIS/CRASHEDFREIGHTERSMOKE.SCENE.MBIN',
			-- 'MODELS/EFFECTS/DEBRIS/CRASHEDFREIGHTERCLOUDS.SCENE.MBIN',
			-- 'MODELS/EFFECTS/DEBRIS/LARGECRASHEDFREIGHTERCLOUDS.SCENE.MBIN',
			-- 'MODELS/EFFECTS/DEBRIS/LARGECRASHEDFREIGHTERSMOKE.SCENE.MBIN',
		},
		MXML_CHANGE_TABLE	= {
			{
				PRECEDING_KEY_WORDS	= 'Children',
				REMOVE				= 'Section'
			}
		}
	},
	{--	|gravity storm|
		MBIN_FILE_SOURCE	= {
			'MODELS/EFFECTS/HEAVYAIR/GRAVITYSTORM/GRAVITYSTORMEMBER.HEAVYAIR.MBIN',
			'MODELS/EFFECTS/HEAVYAIR/GRAVITYSTORM/GRAVITYSTORMGAS.HEAVYAIR.MBIN',
			'MODELS/EFFECTS/HEAVYAIR/GRAVITYSTORM/GRAVITYSTORMSPIKE.HEAVYAIR.MBIN',
			'MODELS/EFFECTS/HEAVYAIR/GRAVITYSTORM/GRAVITYSTORMSPIKEL.HEAVYAIR.MBIN',
			'MODELS/EFFECTS/HEAVYAIR/GRAVITYSTORM/GRAVITYSTORMSPIKEREFRACTION.HEAVYAIR.MBIN',
			'MODELS/EFFECTS/HEAVYAIR/GRAVITYSTORM/SPARK.HEAVYAIR.MBIN',
		},
		EXML_CREATE			= false,
		MXML_CHANGE_TABLE	= {
			{
				VALUE_CHANGE_TABLE 	= {
					{'Number Of Particles',	'@ * 0.1'} -- 4000
				}
			}
		}
	},
	{--	|bubbles|
		MBIN_FILE_SOURCE	= {
			'MODELS/EFFECTS/HEAVYAIR/BUBBLE/BUBBLE.HEAVYAIR.MBIN',
			'MODELS/EFFECTS/HEAVYAIR/BUBBLE/STORMBUBBLE.HEAVYAIR.MBIN',
		},
		EXML_CREATE			= false,
		MXML_CHANGE_TABLE	= {
			{
				VALUE_CHANGE_TABLE 	= {
					{'Number Of Particles',	'@ * 0.36'},	-- 4000
					{'Max Visible Speed',	'@ * 0.4'}		-- 1500
				}
			},
			{
				PRECEDING_KEY_WORDS = 'Scale Range',
				VALUE_CHANGE_TABLE 	= {
					{'X',			'@ * 0.4'},
					{'Y',			'@ * 0.4'}
				}
			},
		}
	},
	{--	|varied rain|
		MBIN_FILE_SOURCE	= {
			'MODELS/EFFECTS/HEAVYAIR/ALPINE/ALPINE2.HEAVYAIR.MBIN',
			'MODELS/EFFECTS/HEAVYAIR/ALPINE/ALPINE3.HEAVYAIR.MBIN',
			'MODELS/EFFECTS/HEAVYAIR/SWAMP/SWAMP2.HEAVYAIR.MBIN',
			'MODELS/EFFECTS/HEAVYAIR/TOXIC/TOXICRAIN1.HEAVYAIR.MBIN',
			'MODELS/EFFECTS/HEAVYAIR/TOXIC/TOXICRAIN2.HEAVYAIR.MBIN',
		},
		EXML_CREATE			= false,
		MXML_CHANGE_TABLE	= {
			{
				VALUE_CHANGE_TABLE 	= {
					{'Number Of Particles',	'@ * 0.8'}
				}
			},
			{
				PRECEDING_KEY_WORDS = 'Amplitude Min',
				VALUE_CHANGE_TABLE 	= {
					{'X',			-1},
					{'Y',			-1}
				}
			},
			{
				PRECEDING_KEY_WORDS = 'Amplitude Max',
				VALUE_CHANGE_TABLE 	= {
					{'X',			1},
					{'Y',			1}
				}
			}
		}
	},
	{--	|snow1 partice|
		MBIN_FILE_SOURCE	= 'MODELS/EFFECTS/HEAVYAIR/SNOW/SNOW1.HEAVYAIR.MBIN',
		EXML_CREATE			= false,
		MXML_CHANGE_TABLE	= {
			{
				VALUE_CHANGE_TABLE 	= {
					{'Min Particle Lifetime',	5},
					{'Max Particle Lifetime',	10},
					{'Fade Time',				0.5}
				}
			}
		}
	},
	{--	|clean space| of dust and plasma clouds
		MBIN_FILE_SOURCE	= 'MODELS/EFFECTS/HEAVYAIR/SPACE/SPACE.SCENE.MBIN',
		MXML_CHANGE_TABLE	= {
			{
				PRECEDING_KEY_WORDS	= 'Children',
				REMOVE				= 'Section'
			}
		}
	},
	{--	dupe line material
		MBIN_FILE_SOURCE	= {
			{
				'MATERIALS/LINE3D.MATERIAL.MBIN',
				'MATERIALS/LINE3D.EMPTY.MATERIAL.MBIN',
				'REMOVE'
			}
		}
	},
	{--	empty the dupe line
		MBIN_FILE_SOURCE	= 'MATERIALS/LINE3D.EMPTY.MATERIAL.MBIN',
		MXML_CHANGE_TABLE	= {
			{
				PRECEDING_KEY_WORDS	= 'Samplers',
				REMOVE				= 'Section'
			}
		}
	},
	{--	no lines
		MBIN_FILE_SOURCE	= 'MODELS/EFFECTS/LINES/LINERENDERER.SCENE.MBIN',
		MXML_CHANGE_TABLE	= {
			{
				SPECIAL_KEY_WORDS	= {'Name', 'MATERIAL'},
				VALUE_CHANGE_TABLE 	= {
					{'Value',		'MATERIALS/LINE3D.EMPTY.MATERIAL.MBIN'}
				}
			},
			{
				SPECIAL_KEY_WORDS	= {'Name', 'MAXNUMLINES'},
				VALUE_CHANGE_TABLE 	= {
					{'Value',		1}
				}
			}
		}
	},
	{--	|pulse - Less speed lines|
		MBIN_FILE_SOURCE	= {
			'MODELS/EFFECTS/SPEEDLINES/MINIJUMPSPEEDLINES.SPEEDLINE.MBIN',
			'MODELS/EFFECTS/SPEEDLINES/MINIJUMPSPEEDLINES2.SPEEDLINE.MBIN',
			'MODELS/EFFECTS/SPEEDLINES/MINIJUMPSPEEDLINES3.SPEEDLINE.MBIN',
			'MODELS/EFFECTS/SPEEDLINES/MINIJUMPSPEEDLINES4.SPEEDLINE.MBIN',
		},
		EXML_CREATE			= false,
		MXML_CHANGE_TABLE	= {
			{
				INTEGER_TO_FLOAT	= 'Preserve',
				MATH_OPERATION 		= '*',
				VALUE_CHANGE_TABLE 	= {
					{'Number Of Particles',	0.08},
					{'Length',				2},
					{'RemoveCylinderRadius',2},
					{'FadeTime',			0.5}
				}
			}
		}
	},
	{--	|boost - Less speed lines|
		MBIN_FILE_SOURCE	= {
			'MODELS/EFFECTS/SPEEDLINES/SPACE.SPEEDLINE.MBIN',
			'MODELS/EFFECTS/SPEEDLINES/SPACE2.SPEEDLINE.MBIN',
			'MODELS/EFFECTS/SPEEDLINES/SPACEBIG.SPEEDLINE.MBIN'
		},
		EXML_CREATE			= false,
		MXML_CHANGE_TABLE	= {
			{
				INTEGER_TO_FLOAT	= 'Preserve',
				MATH_OPERATION 		= '*',
				VALUE_CHANGE_TABLE 	= {
					{'Number Of Particles',	0.04},
					{'Length',				2},
					{'RemoveCylinderRadius',2},
				}
			},
			{
				MATH_OPERATION 		= '+',
				VALUE_CHANGE_TABLE 	= {
					{'MinVisibleSpeed',		5}
				}
			}
		}
	},
	{--	|Remove jetpack smoke| effect from mech and player
		MBIN_FILE_SOURCE	= {
			'MODELS/EFFECTS/PLAYER/JETPACKEFFECTS/STANDARDJETPACKFX/EMITTERS/JETPACKSMOKEEMITTER.PARTICLE.MBIN',
			'MODELS/EFFECTS/PLAYER/JETPACKEFFECTS/BLUEJETPACKFX/EMITTERS/BLUEJETPACKSMOKEEMITTER.PARTICLE.MBIN',
			'MODELS/EFFECTS/PLAYER/JETPACKEFFECTS/GREENJETPACKFX/EMITTERS/GREENJETPACKSMOKEEMITTER.PARTICLE.MBIN',
			'MODELS/EFFECTS/PLAYER/JETPACKEFFECTS/REDJETPACKFX/EMITTERS/REDJETPACKSMOKEEMITTER.PARTICLE.MBIN',
			'MODELS/EFFECTS/PLAYER/JETPACKEFFECTS/MECHJETPACKFX/EMITTERS/MECHJETEMBEREMITTER.PARTICLE.MBIN',
			'MODELS/EFFECTS/PLAYER/JETPACKEFFECTS/MECHJETPACKFX/EMITTERS/MECHJETSMOKEEMITTER.PARTICLE.MBIN',
			'MODELS/EFFECTS/PLAYER/JETPACKEFFECTS/RUINSJETPACK/MIST.PARTICLE.MBIN'
		},
		EXML_CREATE			= false,
		MXML_CHANGE_TABLE	= {
			{
				VALUE_CHANGE_TABLE	= {
					{'StartEnabled', false}
				}
			}
		}
	},
	{--	|Remove trails| jetpack and contrails
		MBIN_FILE_SOURCE	= {
			'MODELS/EFFECTS/TRAILS/PLAYER/JETPACKTRAIL.TRAIL.MBIN',
			'MODELS/EFFECTS/TRAILS/PLAYER/JETPACKELECTRAIL.TRAIL.MBIN',
			'MODELS/EFFECTS/TRAILS/PLAYER/JETPACKFIRETRAIL.TRAIL.MBIN',
			'MODELS/EFFECTS/TRAILS/PLAYER/JETPACKSENTINELTRAIL.TRAIL.MBIN',
			'MODELS/EFFECTS/TRAILS/PLAYER/JETPACKWORMTRAIL.TRAIL.MBIN',
			'MODELS/EFFECTS/TRAILS/SPACECRAFT/CONTRAIL/CONTRAILTRAIL.TRAIL.MBIN',
			'MODELS/EFFECTS/TRAILS/MECH/MECHCONTRAIL.TRAIL.MBIN'
		},
		EXML_CREATE			= false,
		MXML_CHANGE_TABLE	= {
			{
				INTEGER_TO_FLOAT	= 'Preserve',
				VALUE_CHANGE_TABLE 	= {
					{'Width',				0},
					{'Points',				0},
					{'MaxPointsPerFrame',	0},
					{'DistanceThreshold',	0},
					{'PointLife',			0},
					{'FrontPoints',			0},
					{'FrontUvEnd',			0}
				}
			}
		}
	}
}}}}